server:
  port: 8080

spring:
  application:
    name: smart-tourism-system
  datasource:
    url: jdbc:mysql://localhost:3306/smart_tourism?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 88888888
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 智谱 AI（Zhipu AI）
# 这里放的是机密信息，只有服务器知道
zhipu:
  api-key: "f8b1f1a7735a4fd983462fd1953092a3.WmySbGn4eJ9wAszA"
  url: "https://open.bigmodel.cn/api/paas/v4/chat/completions"



# 支付宝沙箱核心配置
alipay:
  appId: "9021000161681082" # 应用ID
  appPrivateKey: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCus2t6BO+kUcpYb7b8scMx/P/mWTbRpUNGGcAMOWP2HDzVnrPIBTrlP3ztXinsPu/1hJ3M9qaVGBbAk5RK+mBrAMyJ7WsVA4f8sPn6YJc1eKiSgNxDZPv1hGvOHyyZdYRr8kIzBG7Cu+yuv6EQWgn9B6fr3aQ8Q9adYGtAUSaaxijxfa4ICDZTfC2Zdzd4OO7xXoVBnZnVYY6In7C4i2RoSGxPqLjI8RMmakxFFnGmZi45PrYWVNRFgr2Sp+udfB5vdYzPZy56sUIPYwTp9pmtPeU1Fa8/P5ORRvOXyHZ7ndHecC4jw/KGKx1zHXy3Gy+iAZ4dvqIcJgak+RAP7Z+9AgMBAAECggEAc3jYU2Cr3VrKekXtF32P3ZyysFjLqSqpGs6uZ+YPMn9bnn81qcH7OcgLFQImh6baCNhNTUrCtM2lTEi/vgdcb52plIk/PDaHTfjUYjAyAf/svFk8Pbej6pZKg4WLfyt0Cb2pD/ugEksQmDjFhv9clsjWr0pi4gqc8ozmly6Ma8Pv+ASSHLIUhv6mngCAkBftzNw02ODyEa5Ilk6watOzY1rLLIzJg7LTkwC4/kz+JS47pedHhQkoweXpQYCvq1X9ptobrVLbp1+JKBXlXQ6N/j3JiEA5ZRf5sOq3RhsIFQtoeDPMC0kkuEL2VOJa5mVsS/VlMuKZc8nfNpkAJnAtQQKBgQD32JaL/7Na9j8DMmsuEMfqHsLh7JKlkF86PcS9ByeJIhfkdNtjme+NJ5i77pGrlq1f7PURM4eeWw8nA41ELzw4N3qLzofpdlJLep3+vE3g6gzAnj7iM4oefkl4Ir9ceft2WoHiTBNoEwyrRTCu/iTh+4O3y17SnaqI/Vmh0nfYJQKBgQC0csmYVsPV3JyHN70OF8lY2urFkSuPCwgzttTQM54LAdYAYfiLccLHEy6VdivpWoaUYZ3TkkVYjX+dFjzRRZSass+TYVoj2ZnJO1AbtT3m79LuNQiZUMY2e/shCFpTFSa9UBCkeJgcGAoKvEacJZUAJCvLTPNE+nAscJPp+HqpuQKBgBAupQ25AUXkJBMaXKMiV1sy7PiBUMXcmkscM1dAO1WZ00OIWba0G071EeTbW8l/SgykVQ/tdGJjgabDdZrJFr546NhuALO+lPr2o5A5TUBtJ63/5w0v3knFZxif9CyejkuY9zgGTZITBFW+a8JRN6lFmcELV0KbJsJRAGQvcMG9AoGBAJ8VB3c/Ht0+5dwrnod7Hu4v6YQNrJop/qwgxlNa/jzz/GdP999vhmkdFxd7G9FZFoZf3NU2Ad7EuDmT7kAMmKsdcvSage5TG0oV+VTEHvOmgI2ywYbweB52hPolNARFBGcn29Qz4N37r3axb4qfc1Gxkc5kY59vLk9vXGeLwRA5AoGARP98jtiAX9lYva7z4nrHwvn+LJXEjQa9RHCqozOPhMfEwjqRQ6XguG0W3WZ4ifml7igq058Msp/H3K/63WuDz8q5uah3WSrIYc9womLTkQqnpjyuEcjR14fQaNPgRtgVXZp0zC/G4OORrWHnc//LzdZT9D4qEvseMpLLZSs6C9w="
  alipayPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg59ru8DVO+M4abJjWYdql0xO8DlYBalXnATcHYFBttSf0fMdBY77xCT6Gke4+/ZFmLoKZI7vbZW+Vx9U/Y/Xs/J3D0PkdatGqYVwqRZBMuNFLl9xTr9O6FtZu4sod25i+Im83z26ItN3gi87PIu48JrQRkPLc1HE/noAcaur4F4rOTon5glDS7v3wJorjgUbkb/wCzBgsBfqHJ6i4C8XwAp8s3+FHDsxYxKqlzi9Z6/s5VYdA+aSnZTBRJvYeBe6+STEJmGRvV2DiUgyW1IfwP+XE6Wvdyp+mCzjuTvHl9DfyzqszarCzXyobRUWtFtod6ttPxJFYDPDmpNQ9N1NvQIDAQAB"
  # 沙箱网关地址（固定不变，千万别填成正式环境的）
  gatewayUrl: "https://openapi-sandbox.dl.alipaydev.com/gateway.do"
  # 付款成功后，页面跳回你前台的哪个网址？(假设你的Vue跑在5173端口)
  returnUrl: "http://localhost:5173/orders"
  # 付款成功后，支付宝偷偷通知你后端的哪个接口？(我们下一步写这个接口)
  notifyUrl: "http://localhost:8080/api/alipay/notify"